### ISSUE TITLE
Hotkeys do not work when a token is selected

### ISSUE THREAD

**Issue by kimitsu** [Moerill/Layer-Hotkeys#5]
Module version: 1.7.0
FVTT version: 0.6.5
Browser: Electron, Chrome, Firefox (Windows 10 x64)

Whenever an actor token is selected, hotkeys seem to stop working.

No errors in console.

**Comment by Moerill** [comment]
this is actually done on purpose, to allow for token actions which are possibly bound to the same keys as your layer hotkeys

**Comment by kimitsu** [comment]
Hmm, what's the point of hotkey settings then? So that people would spend time configuring hotkeys around those token actions only to find out that they are disabled on purpose?..

**Comment by Moerill** [comment]
Why so negative?

Its valid feedback, but how about giving it with a more positive vibe instead? Maybe then i'd be inclined to listen to it and not just being pissed off again, by people "just complaining about free stuff not being as they expect it to be and not consider the feelings of the one person who is nice enough to use his spare time to offer stuff for free."

**Comment by kimitsu** [comment]
I'm sorry if that sounded negative, I was just exemplifying a user experience. Normally, key settings are especially good for resolving such conflicts, for example the default tool hotkeys (1,2,3,4, etc.) are already in conflict with macro hotkeys, so you have to rebind them anyway. I really did not mean to impose or anything. It's just a bit weird to rob your own module of functionality, but that's only if you purposefully disable hotkeys during token selection. If that happens because token intercepts hotkeys somehow, that's totally different story.

**Comment by Moerill** [comment]
I may have overreacted a bit, but i'm kinda loaded, cause people are to frequently kinda rude, unfriendly or expectant that stuff *has* to be done...
I just expect people to treat the devs politely and friendly.

Back to the topic at hand:
I'm not 100% sure why i decided to do this back in the days. This module is kinda ancient for FVTTs lifetime and in all this time, no one had this issue.  
For me thinking about it now its mostly about the order of priority of key inputs and what a user expects to happen when a key is pressed.
My view here was, i think, when a token is selected, the user expects default FVTT behaviour on keypresses. To avoid issues there, like "why doesn't my token move when i press **W**?" i guess i decided to just ignore inputs for this module when a token is selected.

i'm not sure whether i'm in favor of your idea or the view above. Yes, you can modify the keys to avoid them being in conflict with keys FVTT uses, but not everyone does this. And (to my knowledge) there is no way to check whether a key would invoke some kind of FVTT action, when pressed. This is especially difficult, because there are events for "keydown" and "keyup" and fvtt does many, but not all operations on "keyup". so.. not really feasible to catch all that.

**Comment by geoidesic** [comment]
It's easy to work around this issue. Just hit escape first to deselect all tokens, then hit your desired hot key.
